// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wta.proto

package WTA

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Player struct {
	Id                   uint32               `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	FirstName            string               `protobuf:"bytes,2,opt,name=firstName" json:"firstName,omitempty"`
	LastName             string               `protobuf:"bytes,3,opt,name=lastName" json:"lastName,omitempty"`
	IsRightHanded        bool                 `protobuf:"varint,4,opt,name=isRightHanded" json:"isRightHanded,omitempty"`
	BirthDate            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=birthDate" json:"birthDate,omitempty"`
	CountryCode          string               `protobuf:"bytes,6,opt,name=countryCode" json:"countryCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_wta_479ac4c17352c8a8, []int{0}
}
func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (dst *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(dst, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Player) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Player) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Player) GetIsRightHanded() bool {
	if m != nil {
		return m.IsRightHanded
	}
	return false
}

func (m *Player) GetBirthDate() *timestamp.Timestamp {
	if m != nil {
		return m.BirthDate
	}
	return nil
}

func (m *Player) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

type Ranking struct {
	PlayerId             uint32               `protobuf:"varint,1,opt,name=playerId" json:"playerId,omitempty"`
	RankingDate          *timestamp.Timestamp `protobuf:"bytes,2,opt,name=rankingDate" json:"rankingDate,omitempty"`
	Ranking              uint32               `protobuf:"varint,3,opt,name=ranking" json:"ranking,omitempty"`
	RankingPoints        float32              `protobuf:"fixed32,4,opt,name=rankingPoints" json:"rankingPoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Ranking) Reset()         { *m = Ranking{} }
func (m *Ranking) String() string { return proto.CompactTextString(m) }
func (*Ranking) ProtoMessage()    {}
func (*Ranking) Descriptor() ([]byte, []int) {
	return fileDescriptor_wta_479ac4c17352c8a8, []int{1}
}
func (m *Ranking) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ranking.Unmarshal(m, b)
}
func (m *Ranking) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ranking.Marshal(b, m, deterministic)
}
func (dst *Ranking) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ranking.Merge(dst, src)
}
func (m *Ranking) XXX_Size() int {
	return xxx_messageInfo_Ranking.Size(m)
}
func (m *Ranking) XXX_DiscardUnknown() {
	xxx_messageInfo_Ranking.DiscardUnknown(m)
}

var xxx_messageInfo_Ranking proto.InternalMessageInfo

func (m *Ranking) GetPlayerId() uint32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *Ranking) GetRankingDate() *timestamp.Timestamp {
	if m != nil {
		return m.RankingDate
	}
	return nil
}

func (m *Ranking) GetRanking() uint32 {
	if m != nil {
		return m.Ranking
	}
	return 0
}

func (m *Ranking) GetRankingPoints() float32 {
	if m != nil {
		return m.RankingPoints
	}
	return 0
}

type PlayerWithRanking struct {
	Player               *Player  `protobuf:"bytes,1,opt,name=player" json:"player,omitempty"`
	Ranking              *Ranking `protobuf:"bytes,2,opt,name=ranking" json:"ranking,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerWithRanking) Reset()         { *m = PlayerWithRanking{} }
func (m *PlayerWithRanking) String() string { return proto.CompactTextString(m) }
func (*PlayerWithRanking) ProtoMessage()    {}
func (*PlayerWithRanking) Descriptor() ([]byte, []int) {
	return fileDescriptor_wta_479ac4c17352c8a8, []int{2}
}
func (m *PlayerWithRanking) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerWithRanking.Unmarshal(m, b)
}
func (m *PlayerWithRanking) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerWithRanking.Marshal(b, m, deterministic)
}
func (dst *PlayerWithRanking) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerWithRanking.Merge(dst, src)
}
func (m *PlayerWithRanking) XXX_Size() int {
	return xxx_messageInfo_PlayerWithRanking.Size(m)
}
func (m *PlayerWithRanking) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerWithRanking.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerWithRanking proto.InternalMessageInfo

func (m *PlayerWithRanking) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *PlayerWithRanking) GetRanking() *Ranking {
	if m != nil {
		return m.Ranking
	}
	return nil
}

type PlayerIdRequest struct {
	PlayerId             uint32   `protobuf:"varint,1,opt,name=playerId" json:"playerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerIdRequest) Reset()         { *m = PlayerIdRequest{} }
func (m *PlayerIdRequest) String() string { return proto.CompactTextString(m) }
func (*PlayerIdRequest) ProtoMessage()    {}
func (*PlayerIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_wta_479ac4c17352c8a8, []int{3}
}
func (m *PlayerIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerIdRequest.Unmarshal(m, b)
}
func (m *PlayerIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerIdRequest.Marshal(b, m, deterministic)
}
func (dst *PlayerIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerIdRequest.Merge(dst, src)
}
func (m *PlayerIdRequest) XXX_Size() int {
	return xxx_messageInfo_PlayerIdRequest.Size(m)
}
func (m *PlayerIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerIdRequest proto.InternalMessageInfo

func (m *PlayerIdRequest) GetPlayerId() uint32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

type PlayersReply struct {
	Player               []*Player `protobuf:"bytes,1,rep,name=player" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PlayersReply) Reset()         { *m = PlayersReply{} }
func (m *PlayersReply) String() string { return proto.CompactTextString(m) }
func (*PlayersReply) ProtoMessage()    {}
func (*PlayersReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_wta_479ac4c17352c8a8, []int{4}
}
func (m *PlayersReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayersReply.Unmarshal(m, b)
}
func (m *PlayersReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayersReply.Marshal(b, m, deterministic)
}
func (dst *PlayersReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayersReply.Merge(dst, src)
}
func (m *PlayersReply) XXX_Size() int {
	return xxx_messageInfo_PlayersReply.Size(m)
}
func (m *PlayersReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayersReply.DiscardUnknown(m)
}

var xxx_messageInfo_PlayersReply proto.InternalMessageInfo

func (m *PlayersReply) GetPlayer() []*Player {
	if m != nil {
		return m.Player
	}
	return nil
}

func init() {
	proto.RegisterType((*Player)(nil), "WTA.Player")
	proto.RegisterType((*Ranking)(nil), "WTA.Ranking")
	proto.RegisterType((*PlayerWithRanking)(nil), "WTA.PlayerWithRanking")
	proto.RegisterType((*PlayerIdRequest)(nil), "WTA.PlayerIdRequest")
	proto.RegisterType((*PlayersReply)(nil), "WTA.PlayersReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WTAClient is the client API for WTA service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WTAClient interface {
	GetPlayerWithHighestRanking(ctx context.Context, in *PlayerIdRequest, opts ...grpc.CallOption) (*PlayerWithRanking, error)
	GetRankingsByPlayerId(ctx context.Context, in *PlayerIdRequest, opts ...grpc.CallOption) (WTA_GetRankingsByPlayerIdClient, error)
	GetPlayers(ctx context.Context, opts ...grpc.CallOption) (WTA_GetPlayersClient, error)
}

type wTAClient struct {
	cc *grpc.ClientConn
}

func NewWTAClient(cc *grpc.ClientConn) WTAClient {
	return &wTAClient{cc}
}

func (c *wTAClient) GetPlayerWithHighestRanking(ctx context.Context, in *PlayerIdRequest, opts ...grpc.CallOption) (*PlayerWithRanking, error) {
	out := new(PlayerWithRanking)
	err := c.cc.Invoke(ctx, "/WTA.WTA/GetPlayerWithHighestRanking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wTAClient) GetRankingsByPlayerId(ctx context.Context, in *PlayerIdRequest, opts ...grpc.CallOption) (WTA_GetRankingsByPlayerIdClient, error) {
	stream, err := c.cc.NewStream(ctx, &_WTA_serviceDesc.Streams[0], "/WTA.WTA/GetRankingsByPlayerId", opts...)
	if err != nil {
		return nil, err
	}
	x := &wTAGetRankingsByPlayerIdClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WTA_GetRankingsByPlayerIdClient interface {
	Recv() (*Ranking, error)
	grpc.ClientStream
}

type wTAGetRankingsByPlayerIdClient struct {
	grpc.ClientStream
}

func (x *wTAGetRankingsByPlayerIdClient) Recv() (*Ranking, error) {
	m := new(Ranking)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *wTAClient) GetPlayers(ctx context.Context, opts ...grpc.CallOption) (WTA_GetPlayersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_WTA_serviceDesc.Streams[1], "/WTA.WTA/GetPlayers", opts...)
	if err != nil {
		return nil, err
	}
	x := &wTAGetPlayersClient{stream}
	return x, nil
}

type WTA_GetPlayersClient interface {
	Send(*PlayerIdRequest) error
	CloseAndRecv() (*PlayersReply, error)
	grpc.ClientStream
}

type wTAGetPlayersClient struct {
	grpc.ClientStream
}

func (x *wTAGetPlayersClient) Send(m *PlayerIdRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *wTAGetPlayersClient) CloseAndRecv() (*PlayersReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(PlayersReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WTAServer is the server API for WTA service.
type WTAServer interface {
	GetPlayerWithHighestRanking(context.Context, *PlayerIdRequest) (*PlayerWithRanking, error)
	GetRankingsByPlayerId(*PlayerIdRequest, WTA_GetRankingsByPlayerIdServer) error
	GetPlayers(WTA_GetPlayersServer) error
}

func RegisterWTAServer(s *grpc.Server, srv WTAServer) {
	s.RegisterService(&_WTA_serviceDesc, srv)
}

func _WTA_GetPlayerWithHighestRanking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WTAServer).GetPlayerWithHighestRanking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WTA.WTA/GetPlayerWithHighestRanking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WTAServer).GetPlayerWithHighestRanking(ctx, req.(*PlayerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WTA_GetRankingsByPlayerId_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PlayerIdRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WTAServer).GetRankingsByPlayerId(m, &wTAGetRankingsByPlayerIdServer{stream})
}

type WTA_GetRankingsByPlayerIdServer interface {
	Send(*Ranking) error
	grpc.ServerStream
}

type wTAGetRankingsByPlayerIdServer struct {
	grpc.ServerStream
}

func (x *wTAGetRankingsByPlayerIdServer) Send(m *Ranking) error {
	return x.ServerStream.SendMsg(m)
}

func _WTA_GetPlayers_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WTAServer).GetPlayers(&wTAGetPlayersServer{stream})
}

type WTA_GetPlayersServer interface {
	SendAndClose(*PlayersReply) error
	Recv() (*PlayerIdRequest, error)
	grpc.ServerStream
}

type wTAGetPlayersServer struct {
	grpc.ServerStream
}

func (x *wTAGetPlayersServer) SendAndClose(m *PlayersReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *wTAGetPlayersServer) Recv() (*PlayerIdRequest, error) {
	m := new(PlayerIdRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _WTA_serviceDesc = grpc.ServiceDesc{
	ServiceName: "WTA.WTA",
	HandlerType: (*WTAServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlayerWithHighestRanking",
			Handler:    _WTA_GetPlayerWithHighestRanking_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetRankingsByPlayerId",
			Handler:       _WTA_GetRankingsByPlayerId_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetPlayers",
			Handler:       _WTA_GetPlayers_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "wta.proto",
}

func init() { proto.RegisterFile("wta.proto", fileDescriptor_wta_479ac4c17352c8a8) }

var fileDescriptor_wta_479ac4c17352c8a8 = []byte{
	// 456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x86, 0xeb, 0x14, 0xba, 0xdb, 0xc9, 0x76, 0xd1, 0x5a, 0x80, 0xa2, 0x82, 0x44, 0x14, 0x10,
	0xca, 0x05, 0x2f, 0xea, 0x72, 0x00, 0x09, 0x09, 0x6d, 0x41, 0xec, 0x72, 0x00, 0x45, 0x56, 0xa5,
	0x5e, 0x71, 0x13, 0x37, 0xb5, 0xda, 0xc6, 0x21, 0x76, 0x41, 0x7d, 0x1e, 0x5e, 0x88, 0x03, 0x0f,
	0x84, 0x6a, 0xc7, 0x69, 0x7a, 0x28, 0x7b, 0xf3, 0xfc, 0xfe, 0xc7, 0xfe, 0xe6, 0xd7, 0x40, 0xff,
	0x97, 0x66, 0xa4, 0xac, 0xa4, 0x96, 0xb8, 0x3b, 0x9d, 0x5c, 0x0f, 0x9f, 0xe5, 0x52, 0xe6, 0x2b,
	0x7e, 0x69, 0xa4, 0xd9, 0x66, 0x7e, 0xa9, 0xc5, 0x9a, 0x2b, 0xcd, 0xd6, 0xa5, 0x75, 0x45, 0x7f,
	0x11, 0xf4, 0x92, 0x15, 0xdb, 0xf2, 0x0a, 0x9f, 0x83, 0x27, 0xb2, 0x00, 0x85, 0x28, 0x1e, 0x50,
	0x4f, 0x64, 0xf8, 0x29, 0xf4, 0xe7, 0xa2, 0x52, 0xfa, 0x1b, 0x5b, 0xf3, 0xc0, 0x0b, 0x51, 0xdc,
	0xa7, 0x7b, 0x01, 0x0f, 0xe1, 0x74, 0xc5, 0xea, 0xcb, 0xae, 0xb9, 0x6c, 0x6a, 0xfc, 0x02, 0x06,
	0x42, 0x51, 0x91, 0x2f, 0xf4, 0x2d, 0x2b, 0x32, 0x9e, 0x05, 0xf7, 0x42, 0x14, 0x9f, 0xd2, 0x43,
	0x11, 0xbf, 0x85, 0xfe, 0x4c, 0x54, 0x7a, 0xf1, 0x89, 0x69, 0x1e, 0xdc, 0x0f, 0x51, 0xec, 0x8f,
	0x86, 0xc4, 0xf2, 0x12, 0xc7, 0x4b, 0x26, 0x8e, 0x97, 0xee, 0xcd, 0x38, 0x04, 0x3f, 0x95, 0x9b,
	0x42, 0x57, 0xdb, 0x8f, 0x32, 0xe3, 0x41, 0xcf, 0x7c, 0xdf, 0x96, 0xa2, 0xdf, 0x08, 0x4e, 0x28,
	0x2b, 0x96, 0xa2, 0xc8, 0x77, 0xa4, 0xa5, 0x99, 0xf0, 0x8b, 0x9b, 0xae, 0xa9, 0xf1, 0x7b, 0xf0,
	0x2b, 0x6b, 0x33, 0x14, 0xde, 0x9d, 0x14, 0x6d, 0x3b, 0x0e, 0xe0, 0xa4, 0x2e, 0x4d, 0x04, 0x03,
	0xea, 0xca, 0x5d, 0x02, 0xf5, 0x31, 0x91, 0xa2, 0xd0, 0xca, 0x24, 0xe0, 0xd1, 0x43, 0x31, 0xfa,
	0x0e, 0x17, 0x36, 0xfb, 0xa9, 0xd0, 0x0b, 0x87, 0xfb, 0x1c, 0x7a, 0x16, 0xcf, 0xc0, 0xfa, 0x23,
	0x9f, 0x4c, 0x27, 0xd7, 0xc4, 0xfa, 0x68, 0x7d, 0x85, 0x5f, 0xee, 0x7f, 0xb6, 0xcc, 0x67, 0xc6,
	0x55, 0xbf, 0xd1, 0x70, 0x44, 0xaf, 0xe0, 0x41, 0x52, 0xcf, 0x4a, 0xf9, 0x8f, 0x0d, 0x57, 0xfa,
	0x7f, 0x71, 0x44, 0x57, 0x70, 0x66, 0xed, 0x8a, 0xf2, 0x72, 0xb5, 0x3d, 0x60, 0xe9, 0x1e, 0x61,
	0x19, 0xfd, 0x41, 0xb0, 0xdb, 0x35, 0xfc, 0x15, 0x9e, 0xdc, 0x70, 0xbd, 0x1f, 0xe8, 0x56, 0xe4,
	0x0b, 0xae, 0xb4, 0x9b, 0xeb, 0x61, 0xab, 0xb7, 0xa1, 0x19, 0x3e, 0x6e, 0xa9, 0xad, 0x14, 0xa2,
	0x0e, 0xfe, 0x00, 0x8f, 0x6e, 0xb8, 0xeb, 0x56, 0xe3, 0xad, 0xeb, 0x3c, 0xf2, 0xd0, 0x41, 0x00,
	0x51, 0xe7, 0x35, 0xc2, 0xef, 0x00, 0x1a, 0x1e, 0x75, 0xa4, 0xeb, 0xa2, 0xa5, 0xda, 0x99, 0xa3,
	0x4e, 0x8c, 0xc6, 0x6f, 0x20, 0x2c, 0x59, 0xba, 0xd4, 0x64, 0x2d, 0xd2, 0x4a, 0x2a, 0x5e, 0xfd,
	0x14, 0x29, 0x57, 0x24, 0x97, 0x64, 0x2e, 0x66, 0xb2, 0x60, 0x69, 0x2a, 0xc6, 0xe7, 0x9f, 0xdd,
	0x31, 0xd9, 0xad, 0x49, 0x82, 0x66, 0x3d, 0xb3, 0x2f, 0x57, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x92, 0x0d, 0xb2, 0xf8, 0x85, 0x03, 0x00, 0x00,
}
