// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agents-service.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InsertAgentPlayerRequest struct {
	AgentID              uint32   `protobuf:"varint,1,opt,name=agentID,proto3" json:"agentID,omitempty"`
	PlayerID             uint32   `protobuf:"varint,2,opt,name=playerID,proto3" json:"playerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertAgentPlayerRequest) Reset()         { *m = InsertAgentPlayerRequest{} }
func (m *InsertAgentPlayerRequest) String() string { return proto.CompactTextString(m) }
func (*InsertAgentPlayerRequest) ProtoMessage()    {}
func (*InsertAgentPlayerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agents_service_75b0ed66eac14f24, []int{0}
}
func (m *InsertAgentPlayerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertAgentPlayerRequest.Unmarshal(m, b)
}
func (m *InsertAgentPlayerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertAgentPlayerRequest.Marshal(b, m, deterministic)
}
func (dst *InsertAgentPlayerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertAgentPlayerRequest.Merge(dst, src)
}
func (m *InsertAgentPlayerRequest) XXX_Size() int {
	return xxx_messageInfo_InsertAgentPlayerRequest.Size(m)
}
func (m *InsertAgentPlayerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertAgentPlayerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertAgentPlayerRequest proto.InternalMessageInfo

func (m *InsertAgentPlayerRequest) GetAgentID() uint32 {
	if m != nil {
		return m.AgentID
	}
	return 0
}

func (m *InsertAgentPlayerRequest) GetPlayerID() uint32 {
	if m != nil {
		return m.PlayerID
	}
	return 0
}

type InsertAgentPlayerReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertAgentPlayerReply) Reset()         { *m = InsertAgentPlayerReply{} }
func (m *InsertAgentPlayerReply) String() string { return proto.CompactTextString(m) }
func (*InsertAgentPlayerReply) ProtoMessage()    {}
func (*InsertAgentPlayerReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_agents_service_75b0ed66eac14f24, []int{1}
}
func (m *InsertAgentPlayerReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertAgentPlayerReply.Unmarshal(m, b)
}
func (m *InsertAgentPlayerReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertAgentPlayerReply.Marshal(b, m, deterministic)
}
func (dst *InsertAgentPlayerReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertAgentPlayerReply.Merge(dst, src)
}
func (m *InsertAgentPlayerReply) XXX_Size() int {
	return xxx_messageInfo_InsertAgentPlayerReply.Size(m)
}
func (m *InsertAgentPlayerReply) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertAgentPlayerReply.DiscardUnknown(m)
}

var xxx_messageInfo_InsertAgentPlayerReply proto.InternalMessageInfo

func (m *InsertAgentPlayerReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetAgentByIDRequest struct {
	AgentID              uint32   `protobuf:"varint,1,opt,name=agentID,proto3" json:"agentID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAgentByIDRequest) Reset()         { *m = GetAgentByIDRequest{} }
func (m *GetAgentByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetAgentByIDRequest) ProtoMessage()    {}
func (*GetAgentByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agents_service_75b0ed66eac14f24, []int{2}
}
func (m *GetAgentByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAgentByIDRequest.Unmarshal(m, b)
}
func (m *GetAgentByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAgentByIDRequest.Marshal(b, m, deterministic)
}
func (dst *GetAgentByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAgentByIDRequest.Merge(dst, src)
}
func (m *GetAgentByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetAgentByIDRequest.Size(m)
}
func (m *GetAgentByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAgentByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAgentByIDRequest proto.InternalMessageInfo

func (m *GetAgentByIDRequest) GetAgentID() uint32 {
	if m != nil {
		return m.AgentID
	}
	return 0
}

type GetAgentByIDReply struct {
	AgentID              uint32   `protobuf:"varint,1,opt,name=agentID,proto3" json:"agentID,omitempty"`
	Account              uint32   `protobuf:"varint,2,opt,name=account,proto3" json:"account,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAgentByIDReply) Reset()         { *m = GetAgentByIDReply{} }
func (m *GetAgentByIDReply) String() string { return proto.CompactTextString(m) }
func (*GetAgentByIDReply) ProtoMessage()    {}
func (*GetAgentByIDReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_agents_service_75b0ed66eac14f24, []int{3}
}
func (m *GetAgentByIDReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAgentByIDReply.Unmarshal(m, b)
}
func (m *GetAgentByIDReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAgentByIDReply.Marshal(b, m, deterministic)
}
func (dst *GetAgentByIDReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAgentByIDReply.Merge(dst, src)
}
func (m *GetAgentByIDReply) XXX_Size() int {
	return xxx_messageInfo_GetAgentByIDReply.Size(m)
}
func (m *GetAgentByIDReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAgentByIDReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetAgentByIDReply proto.InternalMessageInfo

func (m *GetAgentByIDReply) GetAgentID() uint32 {
	if m != nil {
		return m.AgentID
	}
	return 0
}

func (m *GetAgentByIDReply) GetAccount() uint32 {
	if m != nil {
		return m.Account
	}
	return 0
}

func (m *GetAgentByIDReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*InsertAgentPlayerRequest)(nil), "pb.InsertAgentPlayerRequest")
	proto.RegisterType((*InsertAgentPlayerReply)(nil), "pb.InsertAgentPlayerReply")
	proto.RegisterType((*GetAgentByIDRequest)(nil), "pb.GetAgentByIDRequest")
	proto.RegisterType((*GetAgentByIDReply)(nil), "pb.GetAgentByIDReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentsClient is the client API for Agents service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentsClient interface {
	InsertAgentPlayer(ctx context.Context, in *InsertAgentPlayerRequest, opts ...grpc.CallOption) (*InsertAgentPlayerReply, error)
	GetAgentByID(ctx context.Context, in *GetAgentByIDRequest, opts ...grpc.CallOption) (*GetAgentByIDReply, error)
}

type agentsClient struct {
	cc *grpc.ClientConn
}

func NewAgentsClient(cc *grpc.ClientConn) AgentsClient {
	return &agentsClient{cc}
}

func (c *agentsClient) InsertAgentPlayer(ctx context.Context, in *InsertAgentPlayerRequest, opts ...grpc.CallOption) (*InsertAgentPlayerReply, error) {
	out := new(InsertAgentPlayerReply)
	err := c.cc.Invoke(ctx, "/pb.Agents/InsertAgentPlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentsClient) GetAgentByID(ctx context.Context, in *GetAgentByIDRequest, opts ...grpc.CallOption) (*GetAgentByIDReply, error) {
	out := new(GetAgentByIDReply)
	err := c.cc.Invoke(ctx, "/pb.Agents/GetAgentByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentsServer is the server API for Agents service.
type AgentsServer interface {
	InsertAgentPlayer(context.Context, *InsertAgentPlayerRequest) (*InsertAgentPlayerReply, error)
	GetAgentByID(context.Context, *GetAgentByIDRequest) (*GetAgentByIDReply, error)
}

func RegisterAgentsServer(s *grpc.Server, srv AgentsServer) {
	s.RegisterService(&_Agents_serviceDesc, srv)
}

func _Agents_InsertAgentPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertAgentPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServer).InsertAgentPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Agents/InsertAgentPlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServer).InsertAgentPlayer(ctx, req.(*InsertAgentPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agents_GetAgentByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentsServer).GetAgentByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Agents/GetAgentByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentsServer).GetAgentByID(ctx, req.(*GetAgentByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Agents_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Agents",
	HandlerType: (*AgentsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InsertAgentPlayer",
			Handler:    _Agents_InsertAgentPlayer_Handler,
		},
		{
			MethodName: "GetAgentByID",
			Handler:    _Agents_GetAgentByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agents-service.proto",
}

func init() {
	proto.RegisterFile("agents-service.proto", fileDescriptor_agents_service_75b0ed66eac14f24)
}

var fileDescriptor_agents_service_75b0ed66eac14f24 = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0x4c, 0x4f, 0xcd,
	0x2b, 0x29, 0xd6, 0x2d, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x2a, 0x48, 0x52, 0x0a, 0xe0, 0x92, 0xf0, 0xcc, 0x2b, 0x4e, 0x2d, 0x2a, 0x71, 0x04,
	0xa9, 0x08, 0xc8, 0x49, 0xac, 0x4c, 0x2d, 0x0a, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92,
	0xe0, 0x62, 0x07, 0xeb, 0xf3, 0x74, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0d, 0x82, 0x71, 0x85,
	0xa4, 0xb8, 0x38, 0x0a, 0xc0, 0x4a, 0x3d, 0x5d, 0x24, 0x98, 0xc0, 0x52, 0x70, 0xbe, 0x92, 0x11,
	0x97, 0x18, 0x16, 0x13, 0x0b, 0x72, 0x2a, 0x41, 0xe6, 0x15, 0x97, 0x26, 0x27, 0xa7, 0x16, 0x17,
	0x83, 0xcd, 0xe3, 0x08, 0x82, 0x71, 0x95, 0xf4, 0xb9, 0x84, 0xdd, 0x53, 0x21, 0x1a, 0x9c, 0x2a,
	0x3d, 0x5d, 0x08, 0x3a, 0x40, 0x29, 0x9a, 0x4b, 0x10, 0x55, 0x03, 0xd4, 0x7c, 0x1c, 0xee, 0x05,
	0xc9, 0x24, 0x27, 0xe7, 0x97, 0xe6, 0x95, 0x40, 0x9d, 0x0b, 0xe3, 0x0a, 0x09, 0x71, 0xb1, 0xe4,
	0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2b, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x46, 0xb3, 0x19, 0xb9,
	0xd8, 0xc0, 0x46, 0x17, 0x0b, 0xf9, 0x73, 0x09, 0x62, 0x78, 0x46, 0x48, 0x46, 0xaf, 0x20, 0x49,
	0x0f, 0x57, 0xa8, 0x49, 0x49, 0xe1, 0x90, 0x2d, 0xc8, 0xa9, 0x54, 0x62, 0x10, 0x72, 0xe0, 0xe2,
	0x41, 0x76, 0xb8, 0x90, 0x38, 0x48, 0x35, 0x16, 0xbf, 0x4b, 0x89, 0x62, 0x4a, 0x80, 0x4d, 0x48,
	0x62, 0x03, 0x47, 0x9e, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xbd, 0x27, 0x87, 0x33, 0xd4, 0x01,
	0x00, 0x00,
}
